# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

# Defining the flutter root
flutter_root = File.expand_path('../Flutter', __FILE__)

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  use_modular_headers!

  # Pods for Runner

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

#post_install do |installer|
  #installer.pods_project.targets.each do |target|
    #flutter_additional_ios_build_settings target
  #end

  ################  Awesome Notifications pod modification 1 ###################
  #awesome_pod_file = File.expand_path(File.join('plugins', 'awesome_notifications', 'ios', 'Scripts', 'AwesomePodFile'), '.symlinks')
  #require awesome_pod_file
  #update_awesome_pod_build_settings(installer)
  ################  Awesome Notifications pod modification 1 ###################
#end

################  Awesome Notifications pod modification 2 ###################
#awesome_pod_file = File.expand_path(File.join('plugins', 'awesome_notifications', 'ios', 'Scripts', 'AwesomePodFile'), '.symlinks')
#require awesome_pod_file
#update_awesome_main_target_settings('Runner', File.dirname(File.realpath(__FILE__)), flutter_root)
################  Awesome Notifications pod modification 2 ###################
